import { Injectable, signal } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class TranslateService {

    lang = signal<'es' | 'en'>('es');

    private translations: any = {
        es: {

            header_hola: 'Hola',
            noti_vacio: 'No hay notificaciones',

            configuracion: 'Configuración',
            ajustesCuenta: 'Ajustes de la cuenta',
            subtitulo: 'Personaliza tus preferencias, privacidad, idioma y notificaciones.',
            resumen: 'Resumen',

            // Opciones principales
            preferencias: 'Preferencias',
            opcionesGenerales: 'Opciones generales',
            idioma: 'Idioma',
            guardar: 'Guardar ajustes',
            volver: 'Volver',

            // Notificaciones
            notiEmail: 'Notificaciones por email',
            notiApp: 'Notificaciones en app',
            modoOscuro: 'Modo oscuro',

            // Nuevas opciones
            recordatorios: 'Recordatorios automáticos',
            sincronizacion: 'Sincronización en la nube',
            autoguardado: 'Autoguardado',
            sonidos: 'Sonidos de la app',
            estadisticas: 'Estadísticas avanzadas',

            // Descripciones
            descNotiEmail: 'Recibe avisos importantes.',
            descNotiApp: 'Avisos dentro de la plataforma.',
            descModoOscuro: 'Ajuste visual.',
            descRecordatorios: 'Recibe alertas de tareas importantes.',
            descSincronizacion: 'Guarda tus datos en todos tus dispositivos.',
            descAutoguardado: 'Guarda automáticamente tus cambios.',
            descSonidos: 'Activa sonidos de interacción.',
            descEstadisticas: 'Muestra datos detallados.',

            // Valores dinámicos
            activadas: 'Activadas',
            desactivadas: 'Desactivadas',
            activo: 'Activo',
            inactivo: 'Inactivo',

            // Otros
            email: 'Email',
            perfil: 'Perfil',
            visible: 'Visible',
            privado: 'Privado',
            perfilPublico: 'Perfil público',
            mostrarActividad: 'Mostrar actividad',

            footer_slogan: 'Soluciones financieras con enfoque moderno, claro y seguro.',
            footer_desc: 'Ayudamos a particulares y negocios a tomar mejores decisiones económicas con herramientas digitales, seguimiento preciso y una experiencia diseñada para generar confianza.',

            footer_empresa: 'Empresa',
            footer_sobre: 'Sobre nosotros',
            footer_servicios: 'Servicios',
            footer_contacto: 'Contacto',
            footer_soporte: 'Soporte',

            footer_compromiso: 'Compromiso profesional',
            footer_compromiso_1: 'Atención cercana y especializada',
            footer_compromiso_2: 'Protección de datos y acceso seguro',
            footer_compromiso_3: 'Procesos claros y trazables',
            footer_compromiso_4: 'Mejora continua orientada al cliente',

            footer_colaboradores: 'Empresas colaboradoras',

            footer_vision: 'Visión corporativa',
            footer_vision_title: 'Una plataforma pensada para crecer contigo',
            footer_vision_desc: 'EconomicBalance combina organización financiera, seguimiento personalizado y herramientas de gestión para ofrecer una base estable sobre la que construir decisiones seguras.',

            footer_contacto_prof: 'Contacto profesional',
            footer_email: 'Email',
            footer_telefono: 'Teléfono',
            footer_horario: 'Horario',
            footer_sede: 'Sede',

            footer_privacidad: 'Política de privacidad',
            footer_terminos: 'Términos y condiciones',
            footer_cookies: 'Cookies',

            footer_copy: 'Todos los derechos reservados.',


            sidebar_inicio: 'Inicio',
            sidebar_plantillas: 'Mis Plantillas',
            sidebar_calendario: 'Calendario',
            sidebar_presupuestos: 'Presupuestos',
            sidebar_estadisticas: 'Estadísticas',
            sidebar_soporte: 'Soporte',

            sidebar_modo_oscuro: 'Modo oscuro',
            sidebar_modo_claro: 'Modo claro',
            perfil_editar: 'Editar perfil',
            perfil_ajustes: 'Ajustes',
            perfil_cerrar: 'Cerrar sesión',
            perfil_panel: 'Panel de usuario',
            perfil_editar_titulo: 'Editar perfil',
            perfil_editar_desc: 'Aquí puedes revisar y modificar todos los datos de tu cuenta, además de gestionar la seguridad desde una pantalla dedicada.',
            perfil_volver: 'Volver',

            perfil_subir_foto: 'Subir foto',
            perfil_quitar_foto: 'Quitar foto',

            perfil_sin_correo: 'Sin correo',
            perfil_sin_telefono: 'Sin teléfono',
            perfil_genero_no: 'Género no indicado',

            perfil_id_usuario: 'ID de usuario',
            perfil_estado: 'Estado',
            perfil_activo: 'Activo',
            perfil_seguridad: 'Seguridad',
            perfil_actualizable: 'Actualizable',

            perfil_info_personal: 'Información personal',
            perfil_datos_usuario: 'Datos del usuario',

            perfil_correo: 'Correo electrónico',
            perfil_nombre: 'Nombre',
            perfil_apellidos: 'Apellidos',
            perfil_numero_telefono: 'Número de teléfono',
            perfil_genero: 'Género',
            perfil_selecciona_opcion: 'Selecciona una opción',

            perfil_guardar: 'Guardar cambios',

            perfil_seguridad_titulo: 'Seguridad',
            perfil_actualizar_contra: 'Actualizar contraseña',
            perfil_actualizar_contra_desc: 'Cambia tu contraseña desde una página independiente para hacerlo de forma más clara, cómoda y segura.',
            perfil_ir_actualizar: 'Ir a actualizar contraseña',
            perfil_acceso_especifico: 'Accede a una vista específica para gestionar tu acceso.',

            perfil_proteccion: 'Protección',
            perfil_cambio_seguro: 'Cambio seguro',
            perfil_cambio_seguro_desc: 'Separa la edición del perfil de los datos sensibles.',
            perfil_mas_claridad: 'Más claridad',
            perfil_mas_claridad_desc: 'Evita mezclar información personal con acciones de seguridad.',
            perfil_acceso_rapido: 'Acceso rápido',
            perfil_acceso_rapido_desc: 'Entra directamente a la pantalla de actualización de contraseña.',

            perfil_modal_titulo: 'Cargar foto de perfil',
            perfil_modal_preview: 'Tu foto se verá aquí',
            perfil_modal_preview_desc: 'Selecciona una imagen para previsualizarla',
            perfil_modal_arrastra: 'Arrastra tu foto aquí',
            perfil_modal_o_click: 'o haz clic para seleccionar',
            perfil_modal_cancelar: 'Cancelar',
            perfil_modal_aceptar: 'Aceptar',
            perfil_modal_eliminar: 'Eliminar',
            sidebar_metas_ahorro: "Metas de Ahorro",
            dashboard_resumen_financiero: 'Resumen financiero',
            dashboard_hola: 'Hola',
            dashboard_vision_general: 'Esta es tu visión general',
            dashboard_subtitulo: 'Consulta por separado el estado de tus plantillas y tus metas de ahorro con una vista clara y profesional.',
            dashboard_sesion_activa: 'Sesión activa',

            dashboard_mis_plantillas: 'Mis plantillas',
            dashboard_resumen_movimientos: 'Resumen de movimientos y evolución',
            dashboard_balance_plantillas: 'Balance global calculado desde tus plantillas guardadas.',

            dashboard_saldo_total: 'Saldo total',
            dashboard_balance_acumulado: 'Balance acumulado',
            dashboard_ingresos_mes: 'Ingresos (mes)',
            dashboard_mes_actual: 'Mes actual',
            dashboard_gastos_mes: 'Gastos (mes)',
            dashboard_ahorro_mes: 'Ahorro (mes)',
            dashboard_ingresos_menos_gastos: 'Ingresos - gastos',

            dashboard_evolucion_financiera: 'Evolución financiera de toda la vida',
            dashboard_vista_historica: 'Vista histórica de ingresos y gastos',

            dashboard_mis_ahorros: 'Mis ahorros',
            dashboard_resumen_metas: 'Resumen de metas y progreso',
            dashboard_estado_objetivos: 'Estado actual de tus objetivos y distribución del ahorro.',

            dashboard_total_metas: 'Total metas',
            dashboard_metas_registradas: 'Metas registradas',
            dashboard_metas_activas: 'Metas activas',
            dashboard_pendientes: 'Pendientes',
            dashboard_metas_completadas: 'Metas completadas',
            dashboard_objetivos_cumplidos: 'Objetivos cumplidos',
            dashboard_ahorro_pendiente: 'Ahorro pendiente',
            dashboard_para_completar: 'Para completar metas',

            dashboard_distribucion_ahorro: 'Distribución del ahorro',
            dashboard_cuna_queso: 'Cuña de queso de tus metas',
            dashboard_ultimas_metas: 'Últimas metas',
            dashboard_resumen_rapido: 'Resumen rápido',
            dashboard_no_metas: 'No hay metas registradas todavía.',

            perfil_genero_masculino: 'Masculino',
            perfil_genero_femenino: 'Femenino',
            perfil_genero_otro: 'Otro',
            perfil_genero_no_decir: 'Prefiero no decirlo',

            perfil_modal_click_subir: 'Haz clic para subir una foto',
            perfil_modal_drag_paste: 'Selecciona, arrastra o pega una imagen aquí',
            perfil_modal_eliminar_imagen: 'Eliminar imagen',
            perfil_modal_guardar_foto: 'Guardar foto',
            calendar_planificacion: 'Planificación',
            calendar_titulo: 'Calendario financiero',
            calendar_subtitulo: 'Consulta tus movimientos, recordatorios y fechas clave de un vistazo.',
            calendar_mas: 'más',
            calendar_detalle_tag: 'Detalle del día',
            calendar_sin_descripcion: 'Sin descripción',
            calendar_sin_eventos: 'No hay eventos para este día.',
            metas_ahorro_tag: 'Ahorro',
            metas_titulo: 'Metas de ahorro',
            metas_subtitulo: 'Define objetivos reales, sigue tu progreso y controla tus gastos y ahorros mensuales.',

            nueva_meta: '+ Nueva meta',
            cerrar_formulario: 'Cerrar formulario',
            editar_meta: 'Editar meta',

            titulo: 'Título',
            objetivo: 'Objetivo (€)',
            gastado: 'Gastado (€)',
            fecha_limite: 'Fecha límite',

            guardar_meta: 'Guardar meta',
            guardando: 'Guardando...',
            cancelar: 'Cancelar',

            buscar_meta: 'Escribe el nombre de una meta...',

            presupuesto: 'Presupuesto',
            ahorrado: 'Ahorrado',
            editar: 'Editar',
            quitar: 'Quitar',

            sin_resultados: 'No se encontraron metas con esa búsqueda.',

            exportacion: 'Exportación',
            enviar_resumen: 'Enviar y descargar resumen',
            enviar_correo: 'Enviar por correo',
            enviar_movil: 'Enviar al móvil',
            descargar_excel: 'Descargar Excel',
            support_centro: 'Centro de soporte',
            support_titulo: 'Estamos aquí para ayudarte a resolver cualquier duda',
            support_subtitulo: 'Encuentra respuestas rápidas, consulta preguntas frecuentes y utiliza el asistente virtual para resolver dudas sobre plantillas, calendario o acceso a la cuenta.',

            support_estado: 'Estado del servicio',
            support_disponible: 'Soporte disponible',
            support_estado_desc: 'Nuestro centro de ayuda está operativo y preparado para ofrecer orientación rápida y clara.',

            support_asistente: 'Asistente virtual',
            support_chat_titulo: 'Habla con el chatbot',

            escribiendo: 'Escribiendo...',
            escribe_consulta: 'Escribe tu consulta...',
            enviar: 'Enviar',

            ver_ayuda: 'Ver ayuda',

            faq: 'Preguntas frecuentes',
            faq_titulo: 'Respuestas rápidas',
            ayuda_centro: 'Centro de ayuda',
            ayuda_titulo: 'Estamos aquí para ayudarte',
            ayuda_subtitulo: 'Envía tu consulta al equipo de soporte de Economic Balance y recibe un token para identificar tu solicitud fácilmente.',

            ayuda_estado: 'Estado del servicio',
            ayuda_disponible: 'Soporte disponible',
            ayuda_estado_desc: 'Tu consulta se enviará directamente al equipo de soporte.',

            ayuda_formulario: 'Formulario de soporte',
            ayuda_enviar: 'Enviar solicitud',

            nombre: 'Nombre',
            correo: 'Correo electrónico',
            asunto: 'Asunto',
            mensaje: 'Mensaje',

            placeholder_nombre: 'Introduce tu nombre',
            placeholder_asunto: 'Describe brevemente tu consulta',
            placeholder_mensaje: 'Explica tu problema o consulta con detalle...',

            enviar_solicitud: 'Enviar solicitud',
            enviando: 'Enviando...',
            volver_soporte: 'Volver al soporte',
            token: 'Token de soporte',
            enviado_ok: 'Enviado correctamente',
            enviado_desc: 'Tu solicitud se ha enviado al equipo de soporte. Guarda tu token para futuras consultas.',

        },

        en: {


            noti_vacio: 'No notifications',
            header_hola: 'Hello',
            configuracion: 'Settings',
            ajustesCuenta: 'Account Settings',
            subtitulo: 'Customize your preferences, privacy, language and notifications.',
            resumen: 'Summary',
            preferencias: 'Preferences',
            opcionesGenerales: 'General options',
            idioma: 'Language',
            guardar: 'Save settings',
            volver: 'Back',
            notiEmail: 'Email notifications',
            notiApp: 'In-app notifications',
            modoOscuro: 'Dark mode',
            recordatorios: 'Automatic reminders',
            sincronizacion: 'Cloud sync',
            autoguardado: 'Autosave',
            sonidos: 'App sounds',
            estadisticas: 'Advanced statistics',
            descNotiEmail: 'Receive important alerts.',
            descNotiApp: 'In-app alerts.',
            descModoOscuro: 'Visual adjustment.',
            descRecordatorios: 'Receive alerts for important tasks.',
            descSincronizacion: 'Save your data across devices.',
            descAutoguardado: 'Automatically save your changes.',
            descSonidos: 'Enable interaction sounds.',
            descEstadisticas: 'Show detailed data.',
            activadas: 'Enabled',
            desactivadas: 'Disabled',
            activo: 'Active',
            inactivo: 'Inactive',
            email: 'Email',
            perfil: 'Profile',
            visible: 'Visible',
            privado: 'Private',
            perfilPublico: 'Public profile',
            mostrarActividad: 'Show activity',
            footer_slogan: 'Financial solutions with a modern, clear and secure approach.',
            footer_desc: 'We help individuals and businesses make better economic decisions with digital tools, precise tracking and an experience designed to inspire trust.',
            footer_empresa: 'Company',
            footer_sobre: 'About us',
            footer_servicios: 'Services',
            footer_contacto: 'Contact',
            footer_soporte: 'Support',
            footer_compromiso: 'Professional commitment',
            footer_compromiso_1: 'Close and specialized attention',
            footer_compromiso_2: 'Data protection and secure access',
            footer_compromiso_3: 'Clear and traceable processes',
            footer_compromiso_4: 'Continuous improvement focused on the client',
            footer_colaboradores: 'Partner companies',
            footer_vision: 'Corporate vision',
            footer_vision_title: 'A platform designed to grow with you',
            footer_vision_desc: 'EconomicBalance combines financial organization, personalized tracking and management tools to provide a stable foundation for safe decision-making.',
            footer_contacto_prof: 'Professional contact',
            footer_email: 'Email',
            footer_telefono: 'Phone',
            footer_horario: 'Schedule',
            footer_sede: 'Headquarters',
            footer_privacidad: 'Privacy policy',
            footer_terminos: 'Terms and conditions',
            footer_cookies: 'Cookies',
            footer_copy: 'All rights reserved.',
            sidebar_inicio: 'Home',
            sidebar_plantillas: 'My Templates',
            sidebar_calendario: 'Calendar',
            sidebar_presupuestos: 'Budgets',
            sidebar_estadisticas: 'Statistics',
            sidebar_soporte: 'Support',
            sidebar_modo_oscuro: 'Dark mode',
            sidebar_modo_claro: 'Light mode',
            perfil_editar: 'Edit profile',
            perfil_ajustes: 'Settings',
            perfil_cerrar: 'Log out',
            perfil_panel: 'User panel',
            perfil_editar_titulo: 'Edit profile',
            perfil_editar_desc: 'Here you can review and modify all your account data, as well as manage security from a dedicated screen.',
            perfil_volver: 'Back',
            perfil_subir_foto: 'Upload photo',
            perfil_quitar_foto: 'Remove photo',
            perfil_sin_correo: 'No email',
            perfil_sin_telefono: 'No phone',
            perfil_genero_no: 'Gender not specified',
            perfil_id_usuario: 'User ID',
            perfil_estado: 'Status',
            perfil_activo: 'Active',
            perfil_seguridad: 'Security',
            perfil_actualizable: 'Updatable',
            perfil_info_personal: 'Personal information',
            perfil_datos_usuario: 'User data',
            perfil_correo: 'Email',
            perfil_nombre: 'First name',
            perfil_apellidos: 'Last name',
            perfil_numero_telefono: 'Phone number',
            perfil_genero: 'Gender',
            perfil_selecciona_opcion: 'Select an option',
            perfil_guardar: 'Save changes',
            perfil_seguridad_titulo: 'Security',
            perfil_actualizar_contra: 'Update password',
            perfil_actualizar_contra_desc: 'Change your password from a separate page for a clearer, more comfortable and secure process.',
            perfil_ir_actualizar: 'Go to update password',
            perfil_acceso_especifico: 'Access a specific view to manage your login.',
            perfil_proteccion: 'Protection',
            perfil_cambio_seguro: 'Secure change',
            perfil_cambio_seguro_desc: 'Separate profile editing from sensitive data.',
            perfil_mas_claridad: 'More clarity',
            perfil_mas_claridad_desc: 'Avoid mixing personal information with security actions.',
            perfil_acceso_rapido: 'Quick access',
            perfil_acceso_rapido_desc: 'Go directly to the password update screen.',
            perfil_modal_titulo: 'Upload profile photo',
            perfil_modal_preview: 'Your photo will appear here',
            perfil_modal_preview_desc: 'Select an image to preview it',
            perfil_modal_arrastra: 'Drag your photo here',
            perfil_modal_o_click: 'or click to select',
            perfil_modal_cancelar: 'Cancel',
            perfil_modal_aceptar: 'Accept',
            perfil_modal_eliminar: 'Delete',
            sidebar_metas_ahorro: "Savings Goals",
            dashboard_resumen_financiero: 'Financial overview',
            dashboard_hola: 'Hello',
            dashboard_vision_general: 'This is your general overview',
            dashboard_subtitulo: 'Check separately the status of your templates and your savings goals with a clear and professional view.',
            dashboard_sesion_activa: 'Active session',
            dashboard_mis_plantillas: 'My templates',
            dashboard_resumen_movimientos: 'Movement and trend summary',
            dashboard_balance_plantillas: 'Global balance calculated from your saved templates.',
            dashboard_saldo_total: 'Total balance',
            dashboard_balance_acumulado: 'Accumulated balance',
            dashboard_ingresos_mes: 'Income (month)',
            dashboard_mes_actual: 'Current month',
            dashboard_gastos_mes: 'Expenses (month)',
            dashboard_ahorro_mes: 'Savings (month)',
            dashboard_ingresos_menos_gastos: 'Income - expenses',
            dashboard_evolucion_financiera: 'Lifetime financial evolution',
            dashboard_vista_historica: 'Historical view of income and expenses',
            dashboard_mis_ahorros: 'My savings',
            dashboard_resumen_metas: 'Goals and progress summary',
            dashboard_estado_objetivos: 'Current status of your goals and savings distribution.',
            dashboard_total_metas: 'Total goals',
            dashboard_metas_registradas: 'Registered goals',
            dashboard_metas_activas: 'Active goals',
            dashboard_pendientes: 'Pending',
            dashboard_metas_completadas: 'Completed goals',
            dashboard_objetivos_cumplidos: 'Achieved goals',
            dashboard_ahorro_pendiente: 'Pending savings',
            dashboard_para_completar: 'To complete goals',
            dashboard_distribucion_ahorro: 'Savings distribution',
            dashboard_cuna_queso: 'Your goals cheese chart',
            dashboard_ultimas_metas: 'Latest goals',
            dashboard_resumen_rapido: 'Quick summary',
            dashboard_no_metas: 'There are no registered goals yet.',
            perfil_genero_masculino: 'Male',
            perfil_genero_femenino: 'Female',
            perfil_genero_otro: 'Other',
            perfil_genero_no_decir: 'Prefer not to say',
            perfil_modal_click_subir: 'Click to upload a photo',
            perfil_modal_drag_paste: 'Select, drag or paste an image here',
            perfil_modal_eliminar_imagen: 'Delete image',
            perfil_modal_guardar_foto: 'Save photo',
            calendar_planificacion: 'Planning',
            calendar_titulo: 'Financial calendar',
            calendar_subtitulo: 'Check your movements, reminders and key dates at a glance.',
            calendar_mas: 'more',
            calendar_detalle_tag: 'Day details',
            calendar_sin_descripcion: 'No description',
            calendar_sin_eventos: 'There are no events for this day.',
            metas_ahorro_tag: 'Savings',
            metas_titulo: 'Savings goals',
            metas_subtitulo: 'Define real goals, track progress and control monthly spending and savings.',

            nueva_meta: '+ New goal',
            cerrar_formulario: 'Close form',
            editar_meta: 'Edit goal',

            titulo: 'Title',
            objetivo: 'Target (€)',
            gastado: 'Spent (€)',
            fecha_limite: 'Deadline',

            guardar_meta: 'Save goal',
            guardando: 'Saving...',
            cancelar: 'Cancel',

            buscar_meta: 'Search a goal...',

            presupuesto: 'Budget',
            ahorrado: 'Saved',
            editar: 'Edit',
            quitar: 'Remove',

            sin_resultados: 'No goals found for this search.',

            exportacion: 'Export',
            enviar_resumen: 'Send and download summary',
            enviar_correo: 'Send by email',
            enviar_movil: 'Send to phone',
            descargar_excel: 'Download Excel',
            support_centro: 'Support center',
            support_titulo: 'We are here to help you solve any doubt',
            support_subtitulo: 'Find quick answers, check FAQs and use the virtual assistant to solve questions about templates, calendar or account access.',

            support_estado: 'Service status',
            support_disponible: 'Support available',
            support_estado_desc: 'Our help center is active and ready to provide fast and clear guidance.',

            support_asistente: 'Virtual assistant',
            support_chat_titulo: 'Talk with the chatbot',

            escribiendo: 'Typing...',
            escribe_consulta: 'Write your question...',
            enviar: 'Send',

            ver_ayuda: 'View help',

            faq: 'Frequently asked questions',
            faq_titulo: 'Quick answers',
            ayuda_centro: 'Help center',
            ayuda_titulo: 'We are here to help you',
            ayuda_subtitulo: 'Send your request to the Economic Balance support team and receive a token to identify it easily.',
            ayuda_estado: 'Service status',
            ayuda_disponible: 'Support available',
            ayuda_estado_desc: 'Your request will be sent directly to the support team.',
            ayuda_formulario: 'Support form',
            ayuda_enviar: 'Send request',
            nombre: 'Name',
            correo: 'Email',
            asunto: 'Subject',
            mensaje: 'Message',
            placeholder_nombre: 'Enter your name',
            placeholder_asunto: 'Briefly describe your issue',
            placeholder_mensaje: 'Explain your issue in detail...',
            enviar_solicitud: 'Send request',
            enviando: 'Sending...',
            volver_soporte: 'Back to support',
            token: 'Support token',
            enviado_ok: 'Successfully sent',
            enviado_desc: 'Your request has been sent to support. Save your token for future reference.',
        }
    };

    constructor() {
        const saved = localStorage.getItem('lang');
        if (saved) this.lang.set(saved as 'es' | 'en');
    }

    setLang(lang: 'es' | 'en') {

        this.lang.set(lang);
        localStorage.setItem('lang', lang);
    }

    t(key: string): string {
        return this.translations[this.lang()][key] || key;
    }
}
